### ISSUE TITLE
Composer create-project fails and other issues with installing

### ISSUE THREAD

**Issue by LarryTX** [infoweb-internet-solutions/yii2-cms#47]
Thus far, I've been able to work around some of the issues, but I thought you might like to know that there are serious problems in installing yii2-cms. First, the installation fails with the following message:
```php
[Composer\DependencyResolver\SolverProblemsException]
  Problem 1
    - yiisoft/yii2 dev-master requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery.inputmask 3.1.* -> no matching package found.
    - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.x-dev, dev-master].
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
ceate-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no
rs] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]
```
Whenever, I removed the stablity flag from composer create-project, it installed just fine.
Second, composer create-project creates a vendor directory that contains only one subdirectory, Assets. After running composer require for yii2-cms, I was left with the same situation. Hence, there are no migrations to run.

I tried to remedy this issue by downloading the entire source from Github and replacing the contents of vendor/infoweb-internet-solutions/yii2-cms with the downloaded files. However, after that, when I run the migrations, it errors out with multiple errors:
```
L:\xampp\htdocs\assist>yii migrate/up --migrationPath=@vendor/infoweb-internet-solutions/yii2-cms/migrations
Yii Migration Tool (based on Yii v2.0.3)

Total 3 new migrations to be applied:
        m140930_123135_create_default_auth
        m141001_090124_add_default_permissions
        m150107_074600_create_image_tables

Apply the above migrations? (yes|no) [no]:yes
*** applying m140930_123135_create_default_auth
    > insert into {{%auth_item}} ... done (time: 0.075s)
    > insert into {{%auth_item}} ... done (time: 0.020s)
    > insert into {{%auth_assignment}} ... done (time: 0.077s)
    > insert into {{%auth_item_child}} ... done (time: 0.049s)
*** applied m140930_123135_create_default_auth (time: 0.242s)

*** applying m141001_090124_add_default_permissions
    > insert into {{%auth_item}} ... done (time: 0.076s)
    > insert into {{%auth_item}} ... done (time: 0.023s)
    > insert into {{%auth_item}} ... done (time: 0.023s)
    > insert into {{%auth_item}} ... done (time: 0.020s)
    > insert into {{%auth_item}} ... done (time: 0.024s)
    > insert into {{%auth_item}} ... done (time: 0.020s)
    > insert into {{%auth_item_child}} ... done (time: 0.024s)
    > insert into {{%auth_item_child}} ... done (time: 0.020s)
    > insert into {{%auth_item_child}} ... done (time: 0.024s)
    > insert into {{%auth_item_child}} ... done (time: 0.020s)
    > insert into {{%auth_item_child}} ... done (time: 0.035s)
*** applied m141001_090124_add_default_permissions (time: 0.333s)

*** applying m150107_074600_create_image_tables
    > create table image ... done (time: 0.172s)
    > create index itemId on {{%image}} (itemId) ...Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1072
 Key column 'itemId' doesn't exist in table
The SQL being executed was: CREATE INDEX `itemId` ON `image` (`itemId`)'

in L:\xampp\htdocs\assist\vendor\yiisoft\yii2\db\Schema.php:534

Error Info:
Array
(
    [0] => 42000
    [1] => 1072
    [2] => Key column 'itemId' doesn't exist in table
)

Stack trace:
#0 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\db\Command.php(776): yii\db\Schema->convertException(Object(PDOException), 'CREATE INDEX `i...')
#1 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\db\Migration.php(420): yii\db\Command->execute()
#2 L:\xampp\htdocs\assist\vendor\infoweb-internet-solutions\yii2-cms\migrations\m150107_074600_create_image_tables.php(34): yii\db\Migration->createIn
dex('itemId', '{{%image}}', 'itemId')
#3 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(492): m150107_074600_create_image_tables->up()
#4 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migra
teUp('m150107_074600_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#7 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#8 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('up', Array)
#9 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('up', Array)
#10 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\console\Application.php(161): yii\base\Module->runAction('migrate/up', Array)
#11 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\console\Application.php(137): yii\console\Application->runAction('migrate/up', Array)
#12 L:\xampp\htdocs\assist\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 L:\xampp\htdocs\assist\yii(31): yii\base\Application->run()
#14 {main}
```
Am I missing something? If the issues are on your end, do you have any idea when a workable extension will be available? If I've done something wrong, can you point me in the right direction?

**Comment by infoweb-internet-solutions** [comment]
Thx for pointing this out @LarryTX . I will look into this issue as soon as possible.

**Comment by rubenheymans** [comment]
to solve the last issue: remove m150107_074600_create_image_tables from the migrations folder or add to the migration table
run the migration from this extension first: https://github.com/CostaRico/yii2-images (php yii migrate/up --migrationPath=@vendor/costa-rico/yii2-images/migrations)

I will write an installation script for the cms somewhere in the future, to make things easier, but I don't know when

**Comment by rubenheymans** [comment]
for the first problem, try running composer update without adding yii2-cms to your requirements
if the vendor folder is still empty, that means you are doing something wrong
make sure you install 'php composer.phar global require "fxp/composer-asset-plugin:1.0.0"' to install bower packages

**Comment by LarryTX** [comment]
Well, after having successfully used composer for quite a while, I must be doing something wrong. Here is precisely what I have done:
1. Removed "infoweb-internet-solutions/yii2-cms": "*" from composer.json
2. Ran composer global require fxp/composer-asset-plugin:1.0.0 (I have a composer.bat file on my Windows machine, so I don't need the php or the .phar stuff.)
3. Ran composer require infoweb-internet-solutions/yii2-cms "*" which succeeded with no errors.
4. And what I have in vendor\infoweb-internet-solutions looks like
![vendor_folder](https://cloud.githubusercontent.com/assets/20743/6732740/b58110ca-ce1b-11e4-9d80-45b68f8245cf.jpg)
Any ideas what I might be doing wrong?

**Comment by rubenheymans** [comment]
did you see any errors whil running composer update?
it looks like it's trying to install some assets but fails and stops everything
try adding "minimum-stability": "dev" to your root composer file

**Comment by LarryTX** [comment]
There were no errors in running ```composer update```. However, it's been my experience that composer often just gives up without any messages. However, when I changed to ```"minimum-stability": "dev"```, that seems to have done the trick! The only problem that I had after that was that kartik-v\datecontrol was not installed as a dependency. I added it manually to my requires, and everything went smoothly thereafter.

One more quick question: Is MoxieManager hard-wired into the installation or can I just ignore it? In my application, I'm not going to have any significant media, and I don't want to pay for something that I dn't need.

Thanks a million for your patience. These things can be really tricky.

**Comment by LarryTX** [comment]
Found another issue in infoweb-nternet-solutions\yii2-cms-user\views\admin\update.php on line 37:
```php
<?php echo $this->renderFile('@dektrium/user/views/admin/flash.php') ?>
```
There is no such file in dektrium's extension. I'm not exactly sure what you intended to render at this juncture.

**Comment by rubenheymans** [comment]
you can ignore moxiemanager. I'm going to replace moxiemanager with https://github.com/trippo/ResponsiveFilemanager, but I'm waiting for someone to rewrite this to support composer

I updated the user module.
Our user module extends dektrium's user module, but he releases frequent updates and we can't keep up. I'll rewrite this somewhere soon

**Comment by infoweb-internet-solutions** [comment]
the readme is updated, installation should be clear and run without any errors now
