### ISSUE TITLE
migrate: Invalid path alias: @infoweb/cms/mail

### ISSUE THREAD

**Issue by georgejr** [infoweb-internet-solutions/yii2-cms#50]
Hi

I followed your instructions, but I can't migrate:
./yii migrate/up
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @infoweb/cms/mail'

**Comment by rubenheymans** [comment]
Can you try running `composer update` again, and check for errors.  
Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @infoweb/cms/mail'  
The path alias should be @infoweb/email, check your log files, in what file and which line are you getting this error?

**Comment by georgejr** [comment]
Just followed the instructions from readme.md
           'viewPath' => '@infoweb/cms/mail',
But changed to @infoweb/email
Anyhow after composer update got this


Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @in                                                                                                                               foweb/email'

in /var/www/food/vendor/yiisoft/yii2/BaseYii.php:152

Stack trace:
#0 /var/www/food/vendor/yiisoft/yii2/mail/BaseMailer.php(364): yii\BaseYii::getA                                                                                                                               lias('@infoweb/email')
#1 /var/www/food/vendor/yiisoft/yii2/base/Component.php(169): yii\mail\BaseMaile                                                                                                                               r->setViewPath('@infoweb/email')
#2 /var/www/food/vendor/yiisoft/yii2/BaseYii.php(518): yii\base\Component->__set                                                                                                                               ('viewPath', '@infoweb/email')
#3 /var/www/food/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configur                                                                                                                               e(Object(yii\swiftmailer\Mailer), Array)
#4 [internal function]: yii\base\Object->__construct(Array)
#5 /var/www/food/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->new                                                                                                                               InstanceArgs(Array)
#6 /var/www/food/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->bu                                                                                                                               ild('yii\\swiftmailer...', Array, Array)
#7 /var/www/food/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('yi                                                                                                                               i\\swiftmailer...', Array, Array)
#8 /var/www/food/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\BaseYii::cr                                                                                                                               eateObject(Array)
#9 /var/www/food/vendor/yiisoft/yii2/di/Instance.php(152): yii\di\ServiceLocator                                                                                                                               ->get('mailer')
#10 /var/www/food/vendor/yiisoft/yii2/di/Instance.php(128): yii\di\Instance->get                                                                                                                               (NULL)
#11 /var/www/food/vendor/yiisoft/yii2/log/EmailTarget.php(70): yii\di\Instance::                                                                                                                               ensure('mailer', 'yii\\mail\\Mailer...')
#12 /var/www/food/vendor/yiisoft/yii2/base/Object.php(107): yii\log\EmailTarget-                                                                                                                               >init()
#13 [internal function]: yii\base\Object->__construct(Array)
#14 /var/www/food/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->ne                                                                                                                               wInstanceArgs(Array)
#15 /var/www/food/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->b                                                                                                                               uild('yii\\log\\EmailTa...', Array, Array)
#16 /var/www/food/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('y                                                                                                                               ii\\log\\EmailTa...', Array, Array)
#17 /var/www/food/vendor/yiisoft/yii2/log/Dispatcher.php(101): yii\BaseYii::crea                                                                                                                               teObject(Array)
#18 /var/www/food/vendor/yiisoft/yii2/base/Object.php(107): yii\log\Dispatcher->                                                                                                                               init()
#19 /var/www/food/vendor/yiisoft/yii2/log/Dispatcher.php(89): yii\base\Object->_                                                                                                                               _construct(Array)
#20 [internal function]: yii\log\Dispatcher->__construct(Array)
#21 /var/www/food/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->ne                                                                                                                               wInstanceArgs(Array)
#22 /var/www/food/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->b                                                                                                                               uild('yii\\log\\Dispatc...', Array, Array)
#23 /var/www/food/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('y                                                                                                                               ii\\log\\Dispatc...', Array, Array)
#24 /var/www/food/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\BaseYii::c                                                                                                                               reateObject(Array)
#25 /var/www/food/vendor/yiisoft/yii2/base/Application.php(302): yii\di\ServiceL                                                                                                                               ocator->get('log')
#26 /var/www/food/vendor/yiisoft/yii2/base/Application.php(267): yii\base\Applic                                                                                                                               ation->bootstrap()
#27 /var/www/food/vendor/yiisoft/yii2/console/Application.php(114): yii\base\App                                                                                                                               lication->init()
#28 /var/www/food/vendor/yiisoft/yii2/base/Object.php(107): yii\console\Applicat                                                                                                                               ion->init()
#29 /var/www/food/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object                                                                                                                               ->__construct(Array)
#30 /var/www/food/vendor/yiisoft/yii2/console/Application.php(79): yii\base\Appl                                                                                                                               ication->__construct(Array)
#31 /var/www/food/yii(30): yii\console\Application->__construct(Array)
#32 {main}
PHP Notice:  Trying to get property of non-object in /var/www/food/vendor/yiisof                                                                                                                               t/yii2/log/Dispatcher.php on line 181
PHP Notice:  Trying to get property of non-object in /var/www/food/vendor/yiisof                                                                                                                               t/yii2/log/Dispatcher.php on line 181
PHP Notice:  Trying to get property of non-object in /var/www/food/vendor/yiisof                                                                                                                               t/yii2/log/Dispatcher.php on line 181
PHP Notice:  Trying to get property of non-object in /var/www/food/vendor/yiisof                                                                                                                               t/yii2/log/Dispatcher.php on line 181
PHP Notice:  Trying to get property of non-object in /var/www/food/vendor/yiisof                                                                                                                               t/yii2/log/Dispatcher.php on line 181
PHP Notice:  Trying to get property of non-object in /var/www/food/vendor/yiisof                                                                                                                               t/yii2/log/Dispatcher.php on line 181

**Comment by infoweb-internet-solutions** [comment]
I still think that you used a path alias that is not correct:
**'yii\base\InvalidParamException' with message 'Invalid path alias: @in foweb/email'**

There seems to be a space in your alias
