### ISSUE TITLE
"Please fix following errors" - error message

### ISSUE THREAD

**Issue by uagrace** [infoweb-internet-solutions/yii2-cms#67]
I installed yii2-cms. When I try to add a new user via the console:
`$ yii user/create email@domain.com admin password`
then I get an error message:
`Please fix following errors:`

XDebug said that the problem in the 'firstname':

```
SQLSTATE[HY000]: General error: 1364 Field 'firstname' doesn't have a default value
The SQL being executed was: INSERT INTO `profile` (`user_id`) VALUES (9)
```

![1](https://cloud.githubusercontent.com/assets/4890772/17834322/3edf0072-6743-11e6-90b1-3ee51e215ded.png)

![3](https://cloud.githubusercontent.com/assets/4890772/17834320/3448b126-6743-11e6-85a5-5512f60c6679.png)

**Comment by kurt0015** [comment]
Hi,

In your configuration (backend/config/main.php) what user model did you configure? It should be:
`        'user' => [
            'class' => 'dektrium\user\Module',
            'enableUnconfirmedLogin' => true,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['infoweb', 'admin'],
            'modelMap' => [
                'User' => 'infoweb\user\models\User',
                'UserSearch' => 'infoweb\user\models\UserSearch',
                'Profile' => 'infoweb\user\models\Profile',
            ],
            'controllerMap' => [
                'admin' => 'infoweb\user\controllers\AdminController',
                'settings' => 'infoweb\user\controllers\SettingsController',
                'security' => 'infoweb\user\controllers\SecurityController',
            ],
            'modules' => [
                // Register the custom module as a submodule
                'infoweb-user' => [
                    'class' => 'infoweb\user\Module'
                ]
            ],
        ],`

If that doesn't help please check that you did all the vendor migrations. To run these you should add following code (common/config/main.php):
`'controllerMap' => [
        'migrate' => [
            'class' => 'fishvision\migrate\controllers\MigrateController',
            'autoDiscover' => true,
            'migrationPaths' => [
                '@vendor'
            ],
        ],
    ],`

And run yii migrate/up
